# Generated by Django 5.0.4 on 2025-04-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_studied_today', models.PositiveIntegerField()),
                ('total_time_studied', models.PositiveIntegerField()),
                ('total_days_studied', models.PositiveIntegerField()),
                ('last_entry_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('daily_goal', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
