# Generated by Django 5.0.4 on 2025-04-19 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_studyprogress_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprogress',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='tracker.subject'),
        ),
    ]
