# Generated by Django 5.0.4 on 2025-05-11 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_studyprogress_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyprogress',
            old_name='time_studied_today',
            new_name='time_studied',
        ),
        migrations.RemoveField(
            model_name='studyprogress',
            name='last_entry_date',
        ),
        migrations.RemoveField(
            model_name='studyprogress',
            name='total_days_studied',
        ),
        migrations.RemoveField(
            model_name='studyprogress',
            name='total_time_studied',
        ),
        migrations.AddField(
            model_name='studyprogress',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
