# Generated by Django 5.0.4 on 2025-09-24 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_rename_time_studied_today_studyprogress_time_studied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='daily_goal',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1080)]),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.CheckConstraint(check=models.Q(('daily_goal__lte', 1080), ('daily_goal__gte', 1)), name='daily_goal_range'),
        ),
    ]
