# Generated by Django 5.0.4 on 2025-09-25 12:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_subject_daily_goal_subject_daily_goal_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('new_daily_goal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1080)])),
            ],
        ),
        migrations.RenameField(
            model_name='studyprogress',
            old_name='date',
            new_name='studied_on',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='creation_date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='studyprogress',
            name='time_studied',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='daily_goal',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1080)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='studyprogress',
            constraint=models.CheckConstraint(check=models.Q(('time_studied__gte', 1)), name='studyprogress_time_studied_gte_1'),
        ),
        migrations.AddField(
            model_name='editsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='tracker.subject'),
        ),
        migrations.AddConstraint(
            model_name='editsubject',
            constraint=models.CheckConstraint(check=models.Q(('new_daily_goal__lte', 1080), ('new_daily_goal__gte', 1)), name='edit_subject_daily_goal_range'),
        ),
    ]
