# Generated by Django 5.0.4 on 2025-09-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_editsubject_rename_date_studyprogress_studied_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprogress',
            name='studied_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
