# Generated by Django 5.0.4 on 2025-09-27 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_studyprogress_studied_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editsubject',
            name='new_daily_goal',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Daily goal must be at least 1 minute and not exceed 1080 minutes.'), django.core.validators.MaxValueValidator(1080, message='Daily goal must be at least 1 minute and not exceed 1080 minutes.')]),
        ),
        migrations.AlterField(
            model_name='studyprogress',
            name='time_studied',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Time studied must be at least 1 minute.')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='daily_goal',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Daily goal must be at least 1 minute and not exceed 1080 minutes.'), django.core.validators.MaxValueValidator(1080, message='Daily goal must be at least 1 minute and not exceed 1080 minutes.')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(error_messages={'unique': 'This subject already exists! Please enter a different name.'}, max_length=50, unique=True),
        ),
    ]
