# Generated by Django 5.0.4 on 2025-10-09 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_editsubject_new_daily_goal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(error_messages={'unique': 'This subject already exists! Please enter a different name.'}, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('user', 'name')},
        ),
    ]
