# Generated by Django 5.0.4 on 2025-10-23 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_subject_user_alter_subject_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editsubject',
            name='new_daily_goal',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Daily goal must be at least 1 minute and not exceed 1080 minutes.'), django.core.validators.MaxValueValidator(1080, message='Daily goal must be at least 1 minute and not exceed 1080 minutes.')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='daily_goal',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Daily goal must be at least 1 minute and not exceed 1080 minutes.'), django.core.validators.MaxValueValidator(1080, message='Daily goal must be at least 1 minute and not exceed 1080 minutes.')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
